server:
  port: 8899

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
app.version : 1.0.0
